sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hqp791707571
  alioss:
    access-key-id: LTAI5tEboF1TrkARCWZQzqrk
    access-key-secret: KnOAUqkzyx8WDOECEdHpuypUJhkzAf
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: springboot-web-sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxf1a09dc3dc1c7484
    secret: 4f948a713a89cc4c503429871a320fda
