sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hqp791707571
  alioss:
    access-key-id: LTAI5tEboF1TrkARCWZQzqrk
    access-key-secret: KnOAUqkzyx8WDOECEdHpuypUJhkzAf
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: springboot-web-sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxf1a09dc3dc1c7484
    secret: 4f948a713a89cc4c503429871a320fda
#    由于个人没有资质，所以参数设置为null
    mchid: null
    mch-serial-no: null
    private-key-file-path: null
    api-v3-key: null
    we-chat-pay-cert-file-path: null
    notify-url: http://6f866b56.r8.vip.cpolar.cn/notify/paySuccess
    refund-notify-url:  http://6f866b56.r8.vip.cpolar.cn/notify/paySuccess
  shop:
    address: 福建省厦门市集美区银江路185号
  baidu:
    ak: null
